# Generated by Django 5.1.2 on 2024-10-22 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=300)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=300)),
                ('valor', models.FloatField()),
                ('data', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('N', 'Novo'), ('U', 'Usado')], max_length=1)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.categoria')),
            ],
        ),
    ]
