# Generated by Django 5.1.2 on 2024-11-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data',
        ),
    ]
